---
# DNS server configuration defaults
dns_server_ip: "{{ ansible_default_ipv4.address }}"
dns_forwarders:
  - "8.8.8.8"
  - "8.8.4.4"

# Zone configuration
zone_refresh: 86400      # 1 day
zone_retry: 7200         # 2 hours
zone_expire: 3600000     # ~41 days
zone_minimum: 172800     # 2 days
zone_serial: "{{ ansible_date_time.epoch }}"

allow_transfer:
  - "any"

allow_query:
  - "any"

listen_on:
  - "any"

also_notify:
  - "100.64.51.1"