---
- name: restart bind9
  systemd:
    name: "{{ bind_service }}"
    state: restarted

- name: reload bind9
  systemd:
    name: "{{ bind_service }}"
    state: reloaded

- name: check bind9 status
  systemd:
    name: "{{ bind_service }}"
    state: started
